name: MSIT Telco Service Monitoring

on:
  schedule:
    - cron: '40 23 1-31/2 * *'  # UTC 23:40 (KST 08:40) 홀수날마다 실행
  workflow_dispatch:
    inputs:
      days_range:
        description: '몇 일 전까지의 게시물을 확인할지 설정'
        required: false
        default: '4'
        type: string
      check_sheets:
        description: 'Google Sheets 업데이트 여부'
        required: false
        default: 'true'
        type: boolean
      spreadsheet_name:
        description: 'Google Sheets 스프레드시트 이름'
        required: false
        default: 'MSIT 통신 통계'
        type: string

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        google-chrome --version  # 디버깅용 버전 출력

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          pip install selenium beautifulsoup4 python-telegram-bot requests pandas gspread oauth2client lxml html5lib selenium-stealth webdriver-manager pytesseract
        fi

    - name: Create directories
      run: |
        mkdir -p downloads
        mkdir -p screenshots
        mkdir -p html_content

    - name: Run monitoring script
      env:
        TELCO_NEWS_TOKEN: ${{ secrets.TELCO_NEWS_TOKEN }}
        TELCO_NEWS_TESTER: ${{ secrets.TELCO_NEWS_TESTER }}
        MSIT_GSPREAD_ref: ${{ secrets.MSIT_GSPREAD_ref }}
        MSIT_SPREADSHEET_ID: ${{ secrets.MSIT_SPREADSHEET_ID }}
        DAYS_RANGE: ${{ github.event.inputs.days_range || '4' }}
        CHECK_SHEETS: ${{ github.event.inputs.check_sheets || 'true' }}
        SPREADSHEET_NAME: ${{ github.event.inputs.spreadsheet_name || 'MSIT 통신 통계' }}
        PYTHONIOENCODING: utf-8
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        sleep 2
        
        # 모니터링 스크립트 실행
        echo "모니터링 스크립트 실행..."
        python msit_monitor.py || { echo "모니터링 스크립트 실행 실패"; exit 1; }

    - name: Create simple capture script
      run: |
        echo "import os, sys, time" > simple_capture.py
        echo "from selenium import webdriver" >> simple_capture.py
        echo "from selenium.webdriver.chrome.service import Service" >> simple_capture.py
        echo "from selenium.webdriver.chrome.options import Options" >> simple_capture.py
        echo "from webdriver_manager.chrome import ChromeDriverManager" >> simple_capture.py
        echo "" >> simple_capture.py
        echo "def capture_url(url, output_path):" >> simple_capture.py
        echo "    options = Options()" >> simple_capture.py
        echo "    options.add_argument('--no-sandbox')" >> simple_capture.py
        echo "    options.add_argument('--disable-dev-shm-usage')" >> simple_capture.py
        echo "    options.add_argument('--headless')" >> simple_capture.py
        echo "" >> simple_capture.py
        echo "    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)" >> simple_capture.py
        echo "" >> simple_capture.py
        echo "    try:" >> simple_capture.py
        echo "        print(f\"URL 접속: {url}\")" >> simple_capture.py
        echo "        driver.get(url)" >> simple_capture.py
        echo "        time.sleep(10)  # 로딩 대기" >> simple_capture.py
        echo "" >> simple_capture.py
        echo "        # 스크린샷 저장" >> simple_capture.py
        echo "        driver.save_screenshot(output_path)" >> simple_capture.py
        echo "        print(f\"스크린샷 저장 완료: {output_path}\")" >> simple_capture.py
        echo "" >> simple_capture.py
        echo "        # 페이지 소스 저장" >> simple_capture.py
        echo "        with open('document_content.html', 'w', encoding='utf-8') as f:" >> simple_capture.py
        echo "            f.write(driver.page_source)" >> simple_capture.py
        echo "        print(\"HTML 내용 저장 완료\")" >> simple_capture.py
        echo "" >> simple_capture.py
        echo "        return True" >> simple_capture.py
        echo "    except Exception as e:" >> simple_capture.py
        echo "        print(f\"오류 발생: {str(e)}\")" >> simple_capture.py
        echo "        return False" >> simple_capture.py
        echo "    finally:" >> simple_capture.py
        echo "        driver.quit()" >> simple_capture.py
        echo "" >> simple_capture.py
        echo "if __name__ == \"__main__\":" >> simple_capture.py
        echo "    if len(sys.argv) < 2:" >> simple_capture.py
        echo "        print(\"사용법: python simple_capture.py <URL> [output_path]\")" >> simple_capture.py
        echo "        sys.exit(1)" >> simple_capture.py
        echo "" >> simple_capture.py
        echo "    url = sys.argv[1]" >> simple_capture.py
        echo "    output_path = sys.argv[2] if len(sys.argv) > 2 else \"document_screenshot.png\"" >> simple_capture.py
        echo "" >> simple_capture.py
        echo "    success = capture_url(url, output_path)" >> simple_capture.py
        echo "    if not success:" >> simple_capture.py
        echo "        sys.exit(1)" >> simple_capture.py

    - name: Take screenshots of document (if URL exists)
      if: always()
      run: |
        export DISPLAY=:99
        
        # 로그 파일에서 바로보기 URL 추출
        DOCUMENT_VIEW_URL=$(grep -o "바로보기 URL: [^ ]*" *.log 2>/dev/null | head -1 | sed 's/바로보기 URL: //')
        
        if [ -n "$DOCUMENT_VIEW_URL" ]; then
          echo "바로보기 URL 발견: $DOCUMENT_VIEW_URL"
          python simple_capture.py "$DOCUMENT_VIEW_URL" "html_content/document_screenshot.png"
        else
          echo "바로보기 URL을 찾을 수 없음"
        fi

    - name: Archive artifacts
      if: always()
      run: |
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        mkdir -p artifacts
        cp -r *.log *.png *.html downloads/* screenshots/* html_content/* *.bak artifacts/ 2>/dev/null || true
        echo "실행 정보:" > artifacts/run_info.txt
        echo "실행 ID: ${{ github.run_id }}" >> artifacts/run_info.txt
        echo "실행 번호: ${{ github.run_number }}" >> artifacts/run_info.txt
        echo "타임스탬프: ${TIMESTAMP}" >> artifacts/run_info.txt
        echo "실행자: ${{ github.actor }}" >> artifacts/run_info.txt
        echo "워크플로우: ${{ github.workflow }}" >> artifacts/run_info.txt
        tar -czf monitoring-artifacts-${TIMESTAMP}.tar.gz artifacts/
        echo "ARTIFACT_PATH=monitoring-artifacts-${TIMESTAMP}.tar.gz" >> $GITHUB_ENV
        echo "ARTIFACT_NAME=monitoring-artifacts-${TIMESTAMP}" >> $GITHUB_ENV
        echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV

    - name: Create Release
      if: always()
      uses: softprops/action-gh-release@v1
      with:
        tag_name: monitoring-${{ env.TIMESTAMP }}
        name: 모니터링 실행 ${{ github.run_number }} (${{ env.TIMESTAMP }})
        files: ${{ env.ARTIFACT_PATH }}
        body: |
          ## MSIT 통신 통계 모니터링 실행 결과
          - **실행 ID**: ${{ github.run_id }}
          - **실행 번호**: ${{ github.run_number }}
          - **실행 시간**: ${{ env.TIMESTAMP }}
          - **실행 유형**: ${{ github.event_name }}
          이 릴리스에는 모니터링 스크립트 실행 결과와 관련 로그 및 스크린샷이 포함되어 있습니다.
        token: ${{ secrets.GITHUB_TOKEN }}
