name: Telco News Forwarder

on:
  schedule:
    - cron: '30 23 * * *'  # UTC 23:30 = KST 08:30
  workflow_dispatch:

jobs:
  forward:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot

    - name: Run forwarder script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELCO_NEWS_TOKEN }}
        TELCO_NEWS_RECEIVE: ${{ secrets.TELCO_NEWS_RECEIVE }}
        TELCO_NEWS_BROADCAST_1: ${{ secrets.TELCO_NEWS_BROADCAST_1 }}
        TELCO_NEWS_BROADCAST_2: ${{ secrets.TELCO_NEWS_BROADCAST_2 }}
      run: |
        python telco_news_forwarder.py
